#!/usr/bin/env ruby

# Load bundler, and then load up our environmental variables.
require 'bundler'
Bundler.require(:default, :console)
require 'dotenv'
Dotenv.load

# Load up our sinatra app that loads everything else.
require File.expand_path('../../eventbox_web', __FILE__)

# Add ability to reload console
def reload
  Pry.save_history
  exec(__FILE__)
end
alias :reload! :reload

# Start up the console
puts "Eventbox Console"
Pry.start